/* valaccodestructmodule.c generated by valac, the Vala compiler
 * generated from valaccodestructmodule.vala, do not modify */

/* valaccodestructmodule.vala
 *
 * Copyright (C) 2006-2009  Jürg Billeter
 * Copyright (C) 2006-2008  Raffaele Sandrini
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 *	Raffaele Sandrini <raffaele@sandrini.ch>
 */


#include <glib.h>
#include <glib-object.h>
#include "valacodegen.h"
#include <vala.h>
#include <valaccode.h>
#include <stdlib.h>
#include <string.h>
#include <valagee.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))
#define _vala_typeregister_function_unref0(var) ((var == NULL) ? NULL : (var = (vala_typeregister_function_unref (var), NULL)))
#define _vala_ccode_declarator_suffix_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_declarator_suffix_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _vala_ccode_base_module_emit_context_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_base_module_emit_context_unref (var), NULL)))

#define VALA_TYPE_GLIB_VALUE (vala_glib_value_get_type ())
#define VALA_GLIB_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GLIB_VALUE, ValaGLibValue))
#define VALA_GLIB_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GLIB_VALUE, ValaGLibValueClass))
#define VALA_IS_GLIB_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GLIB_VALUE))
#define VALA_IS_GLIB_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GLIB_VALUE))
#define VALA_GLIB_VALUE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GLIB_VALUE, ValaGLibValueClass))

typedef struct _ValaGLibValue ValaGLibValue;
typedef struct _ValaGLibValueClass ValaGLibValueClass;
#define _vala_target_value_unref0(var) ((var == NULL) ? NULL : (var = (vala_target_value_unref (var), NULL)))


static gpointer vala_ccode_struct_module_parent_class = NULL;

static void vala_ccode_struct_module_real_generate_struct_declaration (ValaCCodeBaseModule* base,
                                                                ValaStruct* st,
                                                                ValaCCodeFile* decl_space);
static void vala_ccode_struct_module_real_visit_struct (ValaCodeVisitor* base,
                                                 ValaStruct* st);
static void vala_ccode_struct_module_begin_struct_destroy_function (ValaCCodeStructModule* self,
                                                             ValaStruct* st);
static void vala_ccode_struct_module_add_struct_copy_function (ValaCCodeStructModule* self,
                                                        ValaStruct* st);
static void vala_ccode_struct_module_add_struct_destroy_function (ValaCCodeStructModule* self,
                                                           ValaStruct* st);
static void vala_ccode_struct_module_add_struct_dup_function (ValaCCodeStructModule* self,
                                                       ValaStruct* st);
static void vala_ccode_struct_module_add_struct_free_function (ValaCCodeStructModule* self,
                                                        ValaStruct* st);
G_GNUC_INTERNAL GType vala_glib_value_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
G_GNUC_INTERNAL ValaGLibValue* vala_glib_value_new (ValaDataType* value_type,
                                    ValaCCodeExpression* cvalue,
                                    gboolean lvalue);
G_GNUC_INTERNAL ValaGLibValue* vala_glib_value_construct (GType object_type,
                                          ValaDataType* value_type,
                                          ValaCCodeExpression* cvalue,
                                          gboolean lvalue);


static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}


static void
vala_ccode_struct_module_real_generate_struct_declaration (ValaCCodeBaseModule* base,
                                                           ValaStruct* st,
                                                           ValaCCodeFile* decl_space)
{
	ValaCCodeStructModule * self;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	ValaCodeContext* _tmp37_;
	ValaCodeContext* _tmp38_;
	ValaProfile _tmp39_;
	ValaProfile _tmp40_;
	ValaStruct* _tmp59_;
	ValaStruct* _tmp60_;
	ValaCCodeStruct* instance_struct = NULL;
	gchar* _tmp81_;
	gchar* _tmp82_;
	gchar* _tmp83_;
	gchar* _tmp84_;
	ValaCCodeStruct* _tmp85_;
	ValaCCodeStruct* _tmp86_;
	ValaCCodeModifiers _tmp87_ = 0;
	ValaVersionAttribute* _tmp88_;
	ValaVersionAttribute* _tmp89_;
	gboolean _tmp90_;
	gboolean _tmp91_;
	ValaCCodeStruct* _tmp92_;
	ValaCCodeStruct* _tmp93_;
	ValaCCodeModifiers _tmp94_;
	ValaCCodeModifiers _tmp95_;
	ValaStruct* _tmp212_;
	ValaStruct* _tmp213_;
	ValaCCodeFunction* function = NULL;
	gchar* _tmp215_;
	gchar* _tmp216_;
	gchar* _tmp217_;
	gchar* _tmp218_;
	gchar* _tmp219_;
	gchar* _tmp220_;
	ValaCCodeFunction* _tmp221_;
	ValaCCodeFunction* _tmp222_;
	ValaCCodeFunction* _tmp230_;
	gchar* _tmp231_;
	gchar* _tmp232_;
	gchar* _tmp233_;
	gchar* _tmp234_;
	gchar* _tmp235_;
	gchar* _tmp236_;
	ValaCCodeParameter* _tmp237_;
	ValaCCodeParameter* _tmp238_;
	ValaCCodeFunction* _tmp239_;
	gchar* _tmp240_;
	gchar* _tmp241_;
	ValaCCodeFunction* _tmp242_;
	ValaCCodeFunction* _tmp250_;
	gchar* _tmp251_;
	gchar* _tmp252_;
	gchar* _tmp253_;
	gchar* _tmp254_;
	ValaCCodeParameter* _tmp255_;
	ValaCCodeParameter* _tmp256_;
	ValaCCodeFunction* _tmp257_;
	self = (ValaCCodeStructModule*) base;
	g_return_if_fail (st != NULL);
	g_return_if_fail (decl_space != NULL);
	_tmp0_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_ccode_base_module_add_symbol_declaration ((ValaCCodeBaseModule*) self, decl_space, (ValaSymbol*) st, _tmp1_);
	_g_free0 (_tmp1_);
	if (_tmp2_) {
		return;
	}
	if (vala_struct_is_boolean_type (st)) {
		_tmp4_ = TRUE;
	} else {
		_tmp4_ = vala_struct_is_integer_type (st);
	}
	if (_tmp4_) {
		_tmp3_ = TRUE;
	} else {
		_tmp3_ = vala_struct_is_floating_type (st);
	}
	if (_tmp3_) {
		ValaStruct* _tmp5_;
		ValaStruct* _tmp6_;
		_tmp5_ = vala_struct_get_base_struct (st);
		_tmp6_ = _tmp5_;
		if (_tmp6_ != NULL) {
			ValaStruct* _tmp7_;
			ValaStruct* _tmp8_;
			ValaStruct* _tmp9_;
			ValaStruct* _tmp10_;
			gchar* _tmp11_;
			gchar* _tmp12_;
			gchar* _tmp13_;
			gchar* _tmp14_;
			ValaCCodeVariableDeclarator* _tmp15_;
			ValaCCodeVariableDeclarator* _tmp16_;
			ValaCCodeTypeDefinition* _tmp17_;
			ValaCCodeTypeDefinition* _tmp18_;
			_tmp7_ = vala_struct_get_base_struct (st);
			_tmp8_ = _tmp7_;
			vala_ccode_base_module_generate_struct_declaration ((ValaCCodeBaseModule*) self, _tmp8_, decl_space);
			_tmp9_ = vala_struct_get_base_struct (st);
			_tmp10_ = _tmp9_;
			_tmp11_ = vala_get_ccode_name ((ValaCodeNode*) _tmp10_);
			_tmp12_ = _tmp11_;
			_tmp13_ = vala_get_ccode_name ((ValaCodeNode*) st);
			_tmp14_ = _tmp13_;
			_tmp15_ = vala_ccode_variable_declarator_new (_tmp14_, NULL, NULL);
			_tmp16_ = _tmp15_;
			_tmp17_ = vala_ccode_type_definition_new (_tmp12_, (ValaCCodeDeclarator*) _tmp16_);
			_tmp18_ = _tmp17_;
			vala_ccode_file_add_type_declaration (decl_space, (ValaCCodeNode*) _tmp18_);
			_vala_ccode_node_unref0 (_tmp18_);
			_vala_ccode_node_unref0 (_tmp16_);
			_g_free0 (_tmp14_);
			_g_free0 (_tmp12_);
		} else {
			gchar* typename = NULL;
			const gchar* _tmp30_;
			gchar* _tmp31_;
			gchar* _tmp32_;
			ValaCCodeVariableDeclarator* _tmp33_;
			ValaCCodeVariableDeclarator* _tmp34_;
			ValaCCodeTypeDefinition* _tmp35_;
			ValaCCodeTypeDefinition* _tmp36_;
			typename = NULL;
			if (vala_struct_is_boolean_type (st)) {
				gchar* _tmp19_;
				vala_ccode_file_add_include (decl_space, "stdbool.h", FALSE);
				_tmp19_ = g_strdup ("bool");
				_g_free0 (typename);
				typename = _tmp19_;
			} else {
				if (vala_struct_is_integer_type (st)) {
					const gchar* _tmp20_ = NULL;
					gboolean _tmp21_;
					gboolean _tmp22_;
					gint _tmp23_;
					gint _tmp24_;
					gchar* _tmp25_;
					vala_ccode_file_add_include (decl_space, "stdint.h", FALSE);
					_tmp21_ = vala_struct_get_signed (st);
					_tmp22_ = _tmp21_;
					if (_tmp22_) {
						_tmp20_ = "";
					} else {
						_tmp20_ = "u";
					}
					_tmp23_ = vala_struct_get_width (st);
					_tmp24_ = _tmp23_;
					_tmp25_ = g_strdup_printf ("%sint%d_t", _tmp20_, _tmp24_);
					_g_free0 (typename);
					typename = _tmp25_;
				} else {
					if (vala_struct_is_floating_type (st)) {
						const gchar* _tmp26_ = NULL;
						gint _tmp27_;
						gint _tmp28_;
						gchar* _tmp29_;
						_tmp27_ = vala_struct_get_width (st);
						_tmp28_ = _tmp27_;
						if (_tmp28_ == 64) {
							_tmp26_ = "double";
						} else {
							_tmp26_ = "float";
						}
						_tmp29_ = g_strdup (_tmp26_);
						_g_free0 (typename);
						typename = _tmp29_;
					}
				}
			}
			_tmp30_ = typename;
			_tmp31_ = vala_get_ccode_name ((ValaCodeNode*) st);
			_tmp32_ = _tmp31_;
			_tmp33_ = vala_ccode_variable_declarator_new (_tmp32_, NULL, NULL);
			_tmp34_ = _tmp33_;
			_tmp35_ = vala_ccode_type_definition_new (_tmp30_, (ValaCCodeDeclarator*) _tmp34_);
			_tmp36_ = _tmp35_;
			vala_ccode_file_add_type_declaration (decl_space, (ValaCCodeNode*) _tmp36_);
			_vala_ccode_node_unref0 (_tmp36_);
			_vala_ccode_node_unref0 (_tmp34_);
			_g_free0 (_tmp32_);
			_g_free0 (typename);
		}
		return;
	}
	_tmp37_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp38_ = _tmp37_;
	_tmp39_ = vala_code_context_get_profile (_tmp38_);
	_tmp40_ = _tmp39_;
	if (_tmp40_ == VALA_PROFILE_GOBJECT) {
		if (vala_get_ccode_has_type_id ((ValaTypeSymbol*) st)) {
			ValaCCodeNewline* _tmp41_;
			ValaCCodeNewline* _tmp42_;
			gchar* macro = NULL;
			gchar* _tmp43_;
			gchar* _tmp44_;
			gchar* _tmp45_;
			gchar* _tmp46_;
			gchar* _tmp47_;
			gchar* _tmp48_;
			const gchar* _tmp49_;
			ValaCCodeMacroReplacement* _tmp50_;
			ValaCCodeMacroReplacement* _tmp51_;
			ValaStructRegisterFunction* type_fun = NULL;
			ValaStructRegisterFunction* _tmp52_;
			ValaStructRegisterFunction* _tmp53_;
			ValaCodeContext* _tmp54_;
			ValaCodeContext* _tmp55_;
			ValaStructRegisterFunction* _tmp56_;
			ValaCCodeFragment* _tmp57_;
			ValaCCodeFragment* _tmp58_;
			vala_ccode_file_add_include (decl_space, "glib-object.h", FALSE);
			_tmp41_ = vala_ccode_newline_new ();
			_tmp42_ = _tmp41_;
			vala_ccode_file_add_type_declaration (decl_space, (ValaCCodeNode*) _tmp42_);
			_vala_ccode_node_unref0 (_tmp42_);
			_tmp43_ = vala_get_ccode_lower_case_name ((ValaCodeNode*) st, NULL);
			_tmp44_ = _tmp43_;
			_tmp45_ = g_strdup_printf ("(%s_get_type ())", _tmp44_);
			_tmp46_ = _tmp45_;
			_g_free0 (_tmp44_);
			macro = _tmp46_;
			_tmp47_ = vala_get_ccode_type_id ((ValaCodeNode*) st);
			_tmp48_ = _tmp47_;
			_tmp49_ = macro;
			_tmp50_ = vala_ccode_macro_replacement_new (_tmp48_, _tmp49_);
			_tmp51_ = _tmp50_;
			vala_ccode_file_add_type_declaration (decl_space, (ValaCCodeNode*) _tmp51_);
			_vala_ccode_node_unref0 (_tmp51_);
			_g_free0 (_tmp48_);
			_tmp52_ = vala_struct_register_function_new (st);
			type_fun = _tmp52_;
			_tmp53_ = type_fun;
			_tmp54_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
			_tmp55_ = _tmp54_;
			vala_typeregister_function_init_from_type ((ValaTypeRegisterFunction*) _tmp53_, _tmp55_, FALSE, TRUE);
			_tmp56_ = type_fun;
			_tmp57_ = vala_typeregister_function_get_declaration ((ValaTypeRegisterFunction*) _tmp56_);
			_tmp58_ = _tmp57_;
			vala_ccode_file_add_type_member_declaration (decl_space, (ValaCCodeNode*) _tmp58_);
			_vala_ccode_node_unref0 (_tmp58_);
			_vala_typeregister_function_unref0 (type_fun);
			_g_free0 (macro);
		}
	}
	_tmp59_ = vala_struct_get_base_struct (st);
	_tmp60_ = _tmp59_;
	if (_tmp60_ == NULL) {
		gchar* _tmp61_;
		gchar* _tmp62_;
		gchar* _tmp63_;
		gchar* _tmp64_;
		gchar* _tmp65_;
		gchar* _tmp66_;
		ValaCCodeVariableDeclarator* _tmp67_;
		ValaCCodeVariableDeclarator* _tmp68_;
		ValaCCodeTypeDefinition* _tmp69_;
		ValaCCodeTypeDefinition* _tmp70_;
		_tmp61_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp62_ = _tmp61_;
		_tmp63_ = g_strdup_printf ("struct _%s", _tmp62_);
		_tmp64_ = _tmp63_;
		_tmp65_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp66_ = _tmp65_;
		_tmp67_ = vala_ccode_variable_declarator_new (_tmp66_, NULL, NULL);
		_tmp68_ = _tmp67_;
		_tmp69_ = vala_ccode_type_definition_new (_tmp64_, (ValaCCodeDeclarator*) _tmp68_);
		_tmp70_ = _tmp69_;
		vala_ccode_file_add_type_declaration (decl_space, (ValaCCodeNode*) _tmp70_);
		_vala_ccode_node_unref0 (_tmp70_);
		_vala_ccode_node_unref0 (_tmp68_);
		_g_free0 (_tmp66_);
		_g_free0 (_tmp64_);
		_g_free0 (_tmp62_);
	} else {
		ValaStruct* _tmp71_;
		ValaStruct* _tmp72_;
		gchar* _tmp73_;
		gchar* _tmp74_;
		gchar* _tmp75_;
		gchar* _tmp76_;
		ValaCCodeVariableDeclarator* _tmp77_;
		ValaCCodeVariableDeclarator* _tmp78_;
		ValaCCodeTypeDefinition* _tmp79_;
		ValaCCodeTypeDefinition* _tmp80_;
		_tmp71_ = vala_struct_get_base_struct (st);
		_tmp72_ = _tmp71_;
		_tmp73_ = vala_get_ccode_name ((ValaCodeNode*) _tmp72_);
		_tmp74_ = _tmp73_;
		_tmp75_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp76_ = _tmp75_;
		_tmp77_ = vala_ccode_variable_declarator_new (_tmp76_, NULL, NULL);
		_tmp78_ = _tmp77_;
		_tmp79_ = vala_ccode_type_definition_new (_tmp74_, (ValaCCodeDeclarator*) _tmp78_);
		_tmp80_ = _tmp79_;
		vala_ccode_file_add_type_declaration (decl_space, (ValaCCodeNode*) _tmp80_);
		_vala_ccode_node_unref0 (_tmp80_);
		_vala_ccode_node_unref0 (_tmp78_);
		_g_free0 (_tmp76_);
		_g_free0 (_tmp74_);
	}
	_tmp81_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp82_ = _tmp81_;
	_tmp83_ = g_strdup_printf ("_%s", _tmp82_);
	_tmp84_ = _tmp83_;
	_tmp85_ = vala_ccode_struct_new (_tmp84_);
	_tmp86_ = _tmp85_;
	_g_free0 (_tmp84_);
	_g_free0 (_tmp82_);
	instance_struct = _tmp86_;
	_tmp88_ = vala_symbol_get_version ((ValaSymbol*) st);
	_tmp89_ = _tmp88_;
	_tmp90_ = vala_version_attribute_get_deprecated (_tmp89_);
	_tmp91_ = _tmp90_;
	if (_tmp91_) {
		_tmp87_ = VALA_CCODE_MODIFIERS_DEPRECATED;
	} else {
		_tmp87_ = 0;
	}
	_tmp92_ = instance_struct;
	_tmp93_ = instance_struct;
	_tmp94_ = vala_ccode_node_get_modifiers ((ValaCCodeNode*) _tmp93_);
	_tmp95_ = _tmp94_;
	vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp93_, _tmp95_ | _tmp87_);
	{
		ValaList* _f_list = NULL;
		ValaList* _tmp96_;
		gint _f_size = 0;
		ValaList* _tmp97_;
		gint _tmp98_;
		gint _tmp99_;
		gint _f_index = 0;
		_tmp96_ = vala_struct_get_fields (st);
		_f_list = _tmp96_;
		_tmp97_ = _f_list;
		_tmp98_ = vala_collection_get_size ((ValaCollection*) _tmp97_);
		_tmp99_ = _tmp98_;
		_f_size = _tmp99_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp100_;
			gint _tmp101_;
			gint _tmp102_;
			ValaField* f = NULL;
			ValaList* _tmp103_;
			gint _tmp104_;
			gpointer _tmp105_;
			ValaField* _tmp106_;
			ValaMemberBinding _tmp107_;
			ValaMemberBinding _tmp108_;
			_tmp100_ = _f_index;
			_f_index = _tmp100_ + 1;
			_tmp101_ = _f_index;
			_tmp102_ = _f_size;
			if (!(_tmp101_ < _tmp102_)) {
				break;
			}
			_tmp103_ = _f_list;
			_tmp104_ = _f_index;
			_tmp105_ = vala_list_get (_tmp103_, _tmp104_);
			f = (ValaField*) _tmp105_;
			_tmp106_ = f;
			_tmp107_ = vala_field_get_binding (_tmp106_);
			_tmp108_ = _tmp107_;
			if (_tmp108_ == VALA_MEMBER_BINDING_INSTANCE) {
				ValaField* _tmp109_;
				ValaDataType* _tmp110_;
				ValaDataType* _tmp111_;
				ValaCCodeModifiers _tmp112_ = 0;
				ValaField* _tmp113_;
				gboolean _tmp114_;
				gboolean _tmp115_;
				ValaCCodeModifiers _tmp116_ = 0;
				ValaField* _tmp117_;
				ValaVersionAttribute* _tmp118_;
				ValaVersionAttribute* _tmp119_;
				gboolean _tmp120_;
				gboolean _tmp121_;
				ValaCCodeModifiers modifiers = 0;
				ValaCCodeStruct* _tmp122_;
				ValaField* _tmp123_;
				ValaDataType* _tmp124_;
				ValaDataType* _tmp125_;
				gchar* _tmp126_;
				gchar* _tmp127_;
				ValaField* _tmp128_;
				gchar* _tmp129_;
				gchar* _tmp130_;
				ValaCCodeModifiers _tmp131_;
				ValaField* _tmp132_;
				ValaDataType* _tmp133_;
				ValaDataType* _tmp134_;
				ValaCCodeDeclaratorSuffix* _tmp135_;
				ValaCCodeDeclaratorSuffix* _tmp136_;
				gboolean _tmp137_ = FALSE;
				ValaField* _tmp138_;
				ValaDataType* _tmp139_;
				ValaDataType* _tmp140_;
				_tmp109_ = f;
				_tmp110_ = vala_variable_get_variable_type ((ValaVariable*) _tmp109_);
				_tmp111_ = _tmp110_;
				vala_ccode_base_module_generate_type_declaration ((ValaCCodeBaseModule*) self, _tmp111_, decl_space);
				_tmp113_ = f;
				_tmp114_ = vala_field_get_is_volatile (_tmp113_);
				_tmp115_ = _tmp114_;
				if (_tmp115_) {
					_tmp112_ = VALA_CCODE_MODIFIERS_VOLATILE;
				} else {
					_tmp112_ = 0;
				}
				_tmp117_ = f;
				_tmp118_ = vala_symbol_get_version ((ValaSymbol*) _tmp117_);
				_tmp119_ = _tmp118_;
				_tmp120_ = vala_version_attribute_get_deprecated (_tmp119_);
				_tmp121_ = _tmp120_;
				if (_tmp121_) {
					_tmp116_ = VALA_CCODE_MODIFIERS_DEPRECATED;
				} else {
					_tmp116_ = 0;
				}
				modifiers = _tmp112_ | _tmp116_;
				_tmp122_ = instance_struct;
				_tmp123_ = f;
				_tmp124_ = vala_variable_get_variable_type ((ValaVariable*) _tmp123_);
				_tmp125_ = _tmp124_;
				_tmp126_ = vala_get_ccode_name ((ValaCodeNode*) _tmp125_);
				_tmp127_ = _tmp126_;
				_tmp128_ = f;
				_tmp129_ = vala_get_ccode_name ((ValaCodeNode*) _tmp128_);
				_tmp130_ = _tmp129_;
				_tmp131_ = modifiers;
				_tmp132_ = f;
				_tmp133_ = vala_variable_get_variable_type ((ValaVariable*) _tmp132_);
				_tmp134_ = _tmp133_;
				_tmp135_ = vala_ccode_base_module_get_ccode_declarator_suffix ((ValaCCodeBaseModule*) self, _tmp134_);
				_tmp136_ = _tmp135_;
				vala_ccode_struct_add_field (_tmp122_, _tmp127_, _tmp130_, _tmp131_, _tmp136_);
				_vala_ccode_declarator_suffix_unref0 (_tmp136_);
				_g_free0 (_tmp130_);
				_g_free0 (_tmp127_);
				_tmp138_ = f;
				_tmp139_ = vala_variable_get_variable_type ((ValaVariable*) _tmp138_);
				_tmp140_ = _tmp139_;
				if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp140_, VALA_TYPE_ARRAY_TYPE)) {
					ValaField* _tmp141_;
					_tmp141_ = f;
					_tmp137_ = vala_get_ccode_array_length ((ValaCodeNode*) _tmp141_);
				} else {
					_tmp137_ = FALSE;
				}
				if (_tmp137_) {
					ValaArrayType* array_type = NULL;
					ValaField* _tmp142_;
					ValaDataType* _tmp143_;
					ValaDataType* _tmp144_;
					ValaArrayType* _tmp145_;
					ValaArrayType* _tmp146_;
					gboolean _tmp147_;
					gboolean _tmp148_;
					_tmp142_ = f;
					_tmp143_ = vala_variable_get_variable_type ((ValaVariable*) _tmp142_);
					_tmp144_ = _tmp143_;
					_tmp145_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp144_, VALA_TYPE_ARRAY_TYPE, ValaArrayType));
					array_type = _tmp145_;
					_tmp146_ = array_type;
					_tmp147_ = vala_array_type_get_fixed_length (_tmp146_);
					_tmp148_ = _tmp147_;
					if (!_tmp148_) {
						ValaDataType* len_type = NULL;
						ValaDataType* _tmp149_;
						ValaDataType* _tmp150_;
						gboolean _tmp173_ = FALSE;
						ValaArrayType* _tmp174_;
						gint _tmp175_;
						gint _tmp176_;
						_tmp149_ = ((ValaCCodeBaseModule*) self)->int_type;
						_tmp150_ = vala_data_type_copy (_tmp149_);
						len_type = _tmp150_;
						{
							gint dim = 0;
							dim = 1;
							{
								gboolean _tmp151_ = FALSE;
								_tmp151_ = TRUE;
								while (TRUE) {
									gint _tmp153_;
									ValaArrayType* _tmp154_;
									gint _tmp155_;
									gint _tmp156_;
									gchar* length_cname = NULL;
									ValaField* _tmp157_;
									gchar* _tmp158_;
									gchar* _tmp159_;
									gboolean _tmp160_;
									ValaCCodeStruct* _tmp168_;
									ValaDataType* _tmp169_;
									gchar* _tmp170_;
									gchar* _tmp171_;
									const gchar* _tmp172_;
									if (!_tmp151_) {
										gint _tmp152_;
										_tmp152_ = dim;
										dim = _tmp152_ + 1;
									}
									_tmp151_ = FALSE;
									_tmp153_ = dim;
									_tmp154_ = array_type;
									_tmp155_ = vala_array_type_get_rank (_tmp154_);
									_tmp156_ = _tmp155_;
									if (!(_tmp153_ <= _tmp156_)) {
										break;
									}
									_tmp157_ = f;
									_tmp158_ = vala_get_ccode_array_length_name ((ValaCodeNode*) _tmp157_);
									_tmp159_ = _tmp158_;
									_tmp160_ = _tmp159_ != NULL;
									_g_free0 (_tmp159_);
									if (_tmp160_) {
										ValaField* _tmp161_;
										gchar* _tmp162_;
										_tmp161_ = f;
										_tmp162_ = vala_get_ccode_array_length_name ((ValaCodeNode*) _tmp161_);
										_g_free0 (length_cname);
										length_cname = _tmp162_;
									} else {
										ValaField* _tmp163_;
										gchar* _tmp164_;
										gchar* _tmp165_;
										gint _tmp166_;
										gchar* _tmp167_;
										_tmp163_ = f;
										_tmp164_ = vala_get_ccode_name ((ValaCodeNode*) _tmp163_);
										_tmp165_ = _tmp164_;
										_tmp166_ = dim;
										_tmp167_ = vala_ccode_base_module_get_array_length_cname ((ValaCCodeBaseModule*) self, _tmp165_, _tmp166_);
										_g_free0 (length_cname);
										length_cname = _tmp167_;
										_g_free0 (_tmp165_);
									}
									_tmp168_ = instance_struct;
									_tmp169_ = len_type;
									_tmp170_ = vala_get_ccode_name ((ValaCodeNode*) _tmp169_);
									_tmp171_ = _tmp170_;
									_tmp172_ = length_cname;
									vala_ccode_struct_add_field (_tmp168_, _tmp171_, _tmp172_, 0, NULL);
									_g_free0 (_tmp171_);
									_g_free0 (length_cname);
								}
							}
						}
						_tmp174_ = array_type;
						_tmp175_ = vala_array_type_get_rank (_tmp174_);
						_tmp176_ = _tmp175_;
						if (_tmp176_ == 1) {
							ValaField* _tmp177_;
							_tmp177_ = f;
							_tmp173_ = vala_symbol_is_internal_symbol ((ValaSymbol*) _tmp177_);
						} else {
							_tmp173_ = FALSE;
						}
						if (_tmp173_) {
							ValaCCodeStruct* _tmp178_;
							ValaDataType* _tmp179_;
							gchar* _tmp180_;
							gchar* _tmp181_;
							ValaField* _tmp182_;
							gchar* _tmp183_;
							gchar* _tmp184_;
							gchar* _tmp185_;
							gchar* _tmp186_;
							_tmp178_ = instance_struct;
							_tmp179_ = len_type;
							_tmp180_ = vala_get_ccode_name ((ValaCodeNode*) _tmp179_);
							_tmp181_ = _tmp180_;
							_tmp182_ = f;
							_tmp183_ = vala_get_ccode_name ((ValaCodeNode*) _tmp182_);
							_tmp184_ = _tmp183_;
							_tmp185_ = vala_ccode_base_module_get_array_size_cname ((ValaCCodeBaseModule*) self, _tmp184_);
							_tmp186_ = _tmp185_;
							vala_ccode_struct_add_field (_tmp178_, _tmp181_, _tmp186_, 0, NULL);
							_g_free0 (_tmp186_);
							_g_free0 (_tmp184_);
							_g_free0 (_tmp181_);
						}
						_vala_code_node_unref0 (len_type);
					}
					_vala_code_node_unref0 (array_type);
				} else {
					gboolean _tmp187_ = FALSE;
					ValaField* _tmp188_;
					ValaDataType* _tmp189_;
					ValaDataType* _tmp190_;
					_tmp188_ = f;
					_tmp189_ = vala_variable_get_variable_type ((ValaVariable*) _tmp188_);
					_tmp190_ = _tmp189_;
					if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp190_, VALA_TYPE_DELEGATE_TYPE)) {
						ValaField* _tmp191_;
						_tmp191_ = f;
						_tmp187_ = vala_get_ccode_delegate_target ((ValaCodeNode*) _tmp191_);
					} else {
						_tmp187_ = FALSE;
					}
					if (_tmp187_) {
						ValaDelegateType* delegate_type = NULL;
						ValaField* _tmp192_;
						ValaDataType* _tmp193_;
						ValaDataType* _tmp194_;
						ValaDelegateType* _tmp195_;
						ValaDelegateType* _tmp196_;
						ValaDelegate* _tmp197_;
						ValaDelegate* _tmp198_;
						gboolean _tmp199_;
						gboolean _tmp200_;
						_tmp192_ = f;
						_tmp193_ = vala_variable_get_variable_type ((ValaVariable*) _tmp192_);
						_tmp194_ = _tmp193_;
						_tmp195_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp194_, VALA_TYPE_DELEGATE_TYPE, ValaDelegateType));
						delegate_type = _tmp195_;
						_tmp196_ = delegate_type;
						_tmp197_ = vala_delegate_type_get_delegate_symbol (_tmp196_);
						_tmp198_ = _tmp197_;
						_tmp199_ = vala_delegate_get_has_target (_tmp198_);
						_tmp200_ = _tmp199_;
						if (_tmp200_) {
							ValaCCodeStruct* _tmp201_;
							ValaField* _tmp202_;
							gchar* _tmp203_;
							gchar* _tmp204_;
							ValaDelegateType* _tmp205_;
							_tmp201_ = instance_struct;
							_tmp202_ = f;
							_tmp203_ = vala_get_ccode_delegate_target_name ((ValaVariable*) _tmp202_);
							_tmp204_ = _tmp203_;
							vala_ccode_struct_add_field (_tmp201_, "gpointer", _tmp204_, 0, NULL);
							_g_free0 (_tmp204_);
							_tmp205_ = delegate_type;
							if (vala_data_type_is_disposable ((ValaDataType*) _tmp205_)) {
								ValaCCodeStruct* _tmp206_;
								ValaField* _tmp207_;
								gchar* _tmp208_;
								gchar* _tmp209_;
								gchar* _tmp210_;
								gchar* _tmp211_;
								_tmp206_ = instance_struct;
								_tmp207_ = f;
								_tmp208_ = vala_get_ccode_name ((ValaCodeNode*) _tmp207_);
								_tmp209_ = _tmp208_;
								_tmp210_ = vala_ccode_base_module_get_delegate_target_destroy_notify_cname ((ValaCCodeBaseModule*) self, _tmp209_);
								_tmp211_ = _tmp210_;
								vala_ccode_struct_add_field (_tmp206_, "GDestroyNotify", _tmp211_, 0, NULL);
								_g_free0 (_tmp211_);
								_g_free0 (_tmp209_);
							}
						}
						_vala_code_node_unref0 (delegate_type);
					}
				}
			}
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	_tmp212_ = vala_struct_get_base_struct (st);
	_tmp213_ = _tmp212_;
	if (_tmp213_ == NULL) {
		ValaCCodeStruct* _tmp214_;
		_tmp214_ = instance_struct;
		vala_ccode_file_add_type_definition (decl_space, (ValaCCodeNode*) _tmp214_);
	}
	_tmp215_ = vala_get_ccode_dup_function ((ValaTypeSymbol*) st);
	_tmp216_ = _tmp215_;
	_tmp217_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp218_ = _tmp217_;
	_tmp219_ = g_strconcat (_tmp218_, "*", NULL);
	_tmp220_ = _tmp219_;
	_tmp221_ = vala_ccode_function_new (_tmp216_, _tmp220_);
	_tmp222_ = _tmp221_;
	_g_free0 (_tmp220_);
	_g_free0 (_tmp218_);
	_g_free0 (_tmp216_);
	function = _tmp222_;
	if (vala_symbol_is_private_symbol ((ValaSymbol*) st)) {
		ValaCCodeFunction* _tmp223_;
		_tmp223_ = function;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp223_, VALA_CCODE_MODIFIERS_STATIC);
	} else {
		gboolean _tmp224_ = FALSE;
		ValaCodeContext* _tmp225_;
		ValaCodeContext* _tmp226_;
		gboolean _tmp227_;
		gboolean _tmp228_;
		_tmp225_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp226_ = _tmp225_;
		_tmp227_ = vala_code_context_get_hide_internal (_tmp226_);
		_tmp228_ = _tmp227_;
		if (_tmp228_) {
			_tmp224_ = vala_symbol_is_internal_symbol ((ValaSymbol*) st);
		} else {
			_tmp224_ = FALSE;
		}
		if (_tmp224_) {
			ValaCCodeFunction* _tmp229_;
			_tmp229_ = function;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp229_, VALA_CCODE_MODIFIERS_INTERNAL);
		}
	}
	_tmp230_ = function;
	_tmp231_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp232_ = _tmp231_;
	_tmp233_ = g_strconcat ("const ", _tmp232_, NULL);
	_tmp234_ = _tmp233_;
	_tmp235_ = g_strconcat (_tmp234_, "*", NULL);
	_tmp236_ = _tmp235_;
	_tmp237_ = vala_ccode_parameter_new ("self", _tmp236_);
	_tmp238_ = _tmp237_;
	vala_ccode_function_add_parameter (_tmp230_, _tmp238_);
	_vala_ccode_node_unref0 (_tmp238_);
	_g_free0 (_tmp236_);
	_g_free0 (_tmp234_);
	_g_free0 (_tmp232_);
	_tmp239_ = function;
	vala_ccode_file_add_function_declaration (decl_space, _tmp239_);
	_tmp240_ = vala_get_ccode_free_function ((ValaTypeSymbol*) st);
	_tmp241_ = _tmp240_;
	_tmp242_ = vala_ccode_function_new (_tmp241_, "void");
	_vala_ccode_node_unref0 (function);
	function = _tmp242_;
	_g_free0 (_tmp241_);
	if (vala_symbol_is_private_symbol ((ValaSymbol*) st)) {
		ValaCCodeFunction* _tmp243_;
		_tmp243_ = function;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp243_, VALA_CCODE_MODIFIERS_STATIC);
	} else {
		gboolean _tmp244_ = FALSE;
		ValaCodeContext* _tmp245_;
		ValaCodeContext* _tmp246_;
		gboolean _tmp247_;
		gboolean _tmp248_;
		_tmp245_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp246_ = _tmp245_;
		_tmp247_ = vala_code_context_get_hide_internal (_tmp246_);
		_tmp248_ = _tmp247_;
		if (_tmp248_) {
			_tmp244_ = vala_symbol_is_internal_symbol ((ValaSymbol*) st);
		} else {
			_tmp244_ = FALSE;
		}
		if (_tmp244_) {
			ValaCCodeFunction* _tmp249_;
			_tmp249_ = function;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp249_, VALA_CCODE_MODIFIERS_INTERNAL);
		}
	}
	_tmp250_ = function;
	_tmp251_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp252_ = _tmp251_;
	_tmp253_ = g_strconcat (_tmp252_, "*", NULL);
	_tmp254_ = _tmp253_;
	_tmp255_ = vala_ccode_parameter_new ("self", _tmp254_);
	_tmp256_ = _tmp255_;
	vala_ccode_function_add_parameter (_tmp250_, _tmp256_);
	_vala_ccode_node_unref0 (_tmp256_);
	_g_free0 (_tmp254_);
	_g_free0 (_tmp252_);
	_tmp257_ = function;
	vala_ccode_file_add_function_declaration (decl_space, _tmp257_);
	if (vala_struct_is_disposable (st)) {
		gchar* _tmp258_;
		gchar* _tmp259_;
		ValaCCodeFunction* _tmp260_;
		ValaCCodeFunction* _tmp268_;
		gchar* _tmp269_;
		gchar* _tmp270_;
		gchar* _tmp271_;
		gchar* _tmp272_;
		gchar* _tmp273_;
		gchar* _tmp274_;
		ValaCCodeParameter* _tmp275_;
		ValaCCodeParameter* _tmp276_;
		ValaCCodeFunction* _tmp277_;
		gchar* _tmp278_;
		gchar* _tmp279_;
		gchar* _tmp280_;
		gchar* _tmp281_;
		ValaCCodeParameter* _tmp282_;
		ValaCCodeParameter* _tmp283_;
		ValaCCodeFunction* _tmp284_;
		gchar* _tmp285_;
		gchar* _tmp286_;
		ValaCCodeFunction* _tmp287_;
		ValaCCodeFunction* _tmp295_;
		gchar* _tmp296_;
		gchar* _tmp297_;
		gchar* _tmp298_;
		gchar* _tmp299_;
		ValaCCodeParameter* _tmp300_;
		ValaCCodeParameter* _tmp301_;
		ValaCCodeFunction* _tmp302_;
		_tmp258_ = vala_get_ccode_copy_function ((ValaTypeSymbol*) st);
		_tmp259_ = _tmp258_;
		_tmp260_ = vala_ccode_function_new (_tmp259_, "void");
		_vala_ccode_node_unref0 (function);
		function = _tmp260_;
		_g_free0 (_tmp259_);
		if (vala_symbol_is_private_symbol ((ValaSymbol*) st)) {
			ValaCCodeFunction* _tmp261_;
			_tmp261_ = function;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp261_, VALA_CCODE_MODIFIERS_STATIC);
		} else {
			gboolean _tmp262_ = FALSE;
			ValaCodeContext* _tmp263_;
			ValaCodeContext* _tmp264_;
			gboolean _tmp265_;
			gboolean _tmp266_;
			_tmp263_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
			_tmp264_ = _tmp263_;
			_tmp265_ = vala_code_context_get_hide_internal (_tmp264_);
			_tmp266_ = _tmp265_;
			if (_tmp266_) {
				_tmp262_ = vala_symbol_is_internal_symbol ((ValaSymbol*) st);
			} else {
				_tmp262_ = FALSE;
			}
			if (_tmp262_) {
				ValaCCodeFunction* _tmp267_;
				_tmp267_ = function;
				vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp267_, VALA_CCODE_MODIFIERS_INTERNAL);
			}
		}
		_tmp268_ = function;
		_tmp269_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp270_ = _tmp269_;
		_tmp271_ = g_strconcat ("const ", _tmp270_, NULL);
		_tmp272_ = _tmp271_;
		_tmp273_ = g_strconcat (_tmp272_, "*", NULL);
		_tmp274_ = _tmp273_;
		_tmp275_ = vala_ccode_parameter_new ("self", _tmp274_);
		_tmp276_ = _tmp275_;
		vala_ccode_function_add_parameter (_tmp268_, _tmp276_);
		_vala_ccode_node_unref0 (_tmp276_);
		_g_free0 (_tmp274_);
		_g_free0 (_tmp272_);
		_g_free0 (_tmp270_);
		_tmp277_ = function;
		_tmp278_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp279_ = _tmp278_;
		_tmp280_ = g_strconcat (_tmp279_, "*", NULL);
		_tmp281_ = _tmp280_;
		_tmp282_ = vala_ccode_parameter_new ("dest", _tmp281_);
		_tmp283_ = _tmp282_;
		vala_ccode_function_add_parameter (_tmp277_, _tmp283_);
		_vala_ccode_node_unref0 (_tmp283_);
		_g_free0 (_tmp281_);
		_g_free0 (_tmp279_);
		_tmp284_ = function;
		vala_ccode_file_add_function_declaration (decl_space, _tmp284_);
		_tmp285_ = vala_get_ccode_destroy_function ((ValaTypeSymbol*) st);
		_tmp286_ = _tmp285_;
		_tmp287_ = vala_ccode_function_new (_tmp286_, "void");
		_vala_ccode_node_unref0 (function);
		function = _tmp287_;
		_g_free0 (_tmp286_);
		if (vala_symbol_is_private_symbol ((ValaSymbol*) st)) {
			ValaCCodeFunction* _tmp288_;
			_tmp288_ = function;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp288_, VALA_CCODE_MODIFIERS_STATIC);
		} else {
			gboolean _tmp289_ = FALSE;
			ValaCodeContext* _tmp290_;
			ValaCodeContext* _tmp291_;
			gboolean _tmp292_;
			gboolean _tmp293_;
			_tmp290_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
			_tmp291_ = _tmp290_;
			_tmp292_ = vala_code_context_get_hide_internal (_tmp291_);
			_tmp293_ = _tmp292_;
			if (_tmp293_) {
				_tmp289_ = vala_symbol_is_internal_symbol ((ValaSymbol*) st);
			} else {
				_tmp289_ = FALSE;
			}
			if (_tmp289_) {
				ValaCCodeFunction* _tmp294_;
				_tmp294_ = function;
				vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp294_, VALA_CCODE_MODIFIERS_INTERNAL);
			}
		}
		_tmp295_ = function;
		_tmp296_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp297_ = _tmp296_;
		_tmp298_ = g_strconcat (_tmp297_, "*", NULL);
		_tmp299_ = _tmp298_;
		_tmp300_ = vala_ccode_parameter_new ("self", _tmp299_);
		_tmp301_ = _tmp300_;
		vala_ccode_function_add_parameter (_tmp295_, _tmp301_);
		_vala_ccode_node_unref0 (_tmp301_);
		_g_free0 (_tmp299_);
		_g_free0 (_tmp297_);
		_tmp302_ = function;
		vala_ccode_file_add_function_declaration (decl_space, _tmp302_);
	}
	_vala_ccode_node_unref0 (function);
	_vala_ccode_node_unref0 (instance_struct);
}


static gpointer
_vala_ccode_base_module_emit_context_ref0 (gpointer self)
{
	return self ? vala_ccode_base_module_emit_context_ref (self) : NULL;
}


static void
vala_ccode_struct_module_real_visit_struct (ValaCodeVisitor* base,
                                            ValaStruct* st)
{
	ValaCCodeStructModule * self;
	ValaCCodeBaseModuleEmitContext* _tmp0_;
	ValaCCodeBaseModuleEmitContext* _tmp1_;
	ValaSourceReference* _tmp2_;
	ValaSourceReference* _tmp3_;
	gboolean _tmp4_ = FALSE;
	ValaCCodeBaseModuleEmitContext* old_instance_finalize_context = NULL;
	ValaCCodeBaseModuleEmitContext* _tmp15_;
	ValaCCodeBaseModuleEmitContext* _tmp16_;
	ValaCCodeBaseModuleEmitContext* _tmp17_;
	ValaCCodeFile* _tmp18_;
	gboolean _tmp21_ = FALSE;
	gboolean _tmp22_ = FALSE;
	gboolean _tmp23_ = FALSE;
	gboolean _tmp24_ = FALSE;
	ValaCCodeBaseModuleEmitContext* _tmp25_;
	ValaCCodeBaseModuleEmitContext* _tmp26_;
	self = (ValaCCodeStructModule*) base;
	g_return_if_fail (st != NULL);
	_tmp0_ = vala_ccode_base_module_emit_context_new ((ValaSymbol*) st);
	_tmp1_ = _tmp0_;
	vala_ccode_base_module_push_context ((ValaCCodeBaseModule*) self, _tmp1_);
	_vala_ccode_base_module_emit_context_unref0 (_tmp1_);
	_tmp2_ = vala_code_node_get_source_reference ((ValaCodeNode*) st);
	_tmp3_ = _tmp2_;
	vala_ccode_base_module_push_line ((ValaCCodeBaseModule*) self, _tmp3_);
	if (vala_get_ccode_has_type_id ((ValaTypeSymbol*) st)) {
		gchar* _tmp5_;
		gchar* _tmp6_;
		gint _tmp7_;
		gint _tmp8_;
		_tmp5_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp6_ = _tmp5_;
		_tmp7_ = strlen (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp4_ = _tmp8_ < 3;
		_g_free0 (_tmp6_);
	} else {
		_tmp4_ = FALSE;
	}
	if (_tmp4_) {
		ValaSourceReference* _tmp9_;
		ValaSourceReference* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		vala_code_node_set_error ((ValaCodeNode*) st, TRUE);
		_tmp9_ = vala_code_node_get_source_reference ((ValaCodeNode*) st);
		_tmp10_ = _tmp9_;
		_tmp11_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp12_ = _tmp11_;
		_tmp13_ = g_strdup_printf ("Name `%s' is too short for struct using GType", _tmp12_);
		_tmp14_ = _tmp13_;
		vala_report_error (_tmp10_, _tmp14_);
		_g_free0 (_tmp14_);
		_g_free0 (_tmp12_);
		return;
	}
	_tmp15_ = ((ValaCCodeBaseModule*) self)->instance_finalize_context;
	_tmp16_ = _vala_ccode_base_module_emit_context_ref0 (_tmp15_);
	old_instance_finalize_context = _tmp16_;
	_tmp17_ = vala_ccode_base_module_emit_context_new (NULL);
	_vala_ccode_base_module_emit_context_unref0 (((ValaCCodeBaseModule*) self)->instance_finalize_context);
	((ValaCCodeBaseModule*) self)->instance_finalize_context = _tmp17_;
	_tmp18_ = ((ValaCCodeBaseModule*) self)->cfile;
	vala_ccode_base_module_generate_struct_declaration ((ValaCCodeBaseModule*) self, st, _tmp18_);
	if (!vala_symbol_is_internal_symbol ((ValaSymbol*) st)) {
		ValaCCodeFile* _tmp19_;
		_tmp19_ = ((ValaCCodeBaseModule*) self)->header_file;
		vala_ccode_base_module_generate_struct_declaration ((ValaCCodeBaseModule*) self, st, _tmp19_);
	}
	if (!vala_symbol_is_private_symbol ((ValaSymbol*) st)) {
		ValaCCodeFile* _tmp20_;
		_tmp20_ = ((ValaCCodeBaseModule*) self)->internal_header_file;
		vala_ccode_base_module_generate_struct_declaration ((ValaCCodeBaseModule*) self, st, _tmp20_);
	}
	if (!vala_struct_is_boolean_type (st)) {
		_tmp22_ = !vala_struct_is_integer_type (st);
	} else {
		_tmp22_ = FALSE;
	}
	if (_tmp22_) {
		_tmp21_ = !vala_struct_is_floating_type (st);
	} else {
		_tmp21_ = FALSE;
	}
	if (_tmp21_) {
		if (vala_struct_is_disposable (st)) {
			vala_ccode_struct_module_begin_struct_destroy_function (self, st);
		}
	}
	vala_code_node_accept_children ((ValaCodeNode*) st, (ValaCodeVisitor*) self);
	if (!vala_struct_is_boolean_type (st)) {
		_tmp24_ = !vala_struct_is_integer_type (st);
	} else {
		_tmp24_ = FALSE;
	}
	if (_tmp24_) {
		_tmp23_ = !vala_struct_is_floating_type (st);
	} else {
		_tmp23_ = FALSE;
	}
	if (_tmp23_) {
		if (vala_struct_is_disposable (st)) {
			vala_ccode_struct_module_add_struct_copy_function (self, st);
			vala_ccode_struct_module_add_struct_destroy_function (self, st);
		}
		vala_ccode_struct_module_add_struct_dup_function (self, st);
		vala_ccode_struct_module_add_struct_free_function (self, st);
	}
	_tmp25_ = old_instance_finalize_context;
	_tmp26_ = _vala_ccode_base_module_emit_context_ref0 (_tmp25_);
	_vala_ccode_base_module_emit_context_unref0 (((ValaCCodeBaseModule*) self)->instance_finalize_context);
	((ValaCCodeBaseModule*) self)->instance_finalize_context = _tmp26_;
	vala_ccode_base_module_pop_line ((ValaCCodeBaseModule*) self);
	vala_ccode_base_module_pop_context ((ValaCCodeBaseModule*) self);
	_vala_ccode_base_module_emit_context_unref0 (old_instance_finalize_context);
}


static void
vala_ccode_struct_module_add_struct_dup_function (ValaCCodeStructModule* self,
                                                  ValaStruct* st)
{
	ValaCCodeFunction* function = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	ValaCCodeFunction* _tmp6_;
	ValaCCodeFunction* _tmp7_;
	ValaSymbolAccessibility _tmp8_;
	ValaSymbolAccessibility _tmp9_;
	ValaCCodeFunction* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	ValaCCodeParameter* _tmp18_;
	ValaCCodeParameter* _tmp19_;
	ValaCCodeFunction* _tmp20_;
	ValaCCodeFunction* _tmp21_;
	ValaCCodeFunction* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	ValaCCodeVariableDeclarator* _tmp27_;
	ValaCCodeVariableDeclarator* _tmp28_;
	ValaCodeContext* _tmp29_;
	ValaCodeContext* _tmp30_;
	ValaProfile _tmp31_;
	ValaProfile _tmp32_;
	ValaCCodeFunction* _tmp113_;
	ValaCCodeFunction* _tmp114_;
	ValaCCodeIdentifier* _tmp115_;
	ValaCCodeIdentifier* _tmp116_;
	ValaCCodeFile* _tmp117_;
	ValaCCodeFunction* _tmp118_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = vala_get_ccode_dup_function ((ValaTypeSymbol*) st);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat (_tmp3_, "*", NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = vala_ccode_function_new (_tmp1_, _tmp5_);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	_g_free0 (_tmp1_);
	function = _tmp7_;
	_tmp8_ = vala_symbol_get_access ((ValaSymbol*) st);
	_tmp9_ = _tmp8_;
	if (_tmp9_ == VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
		ValaCCodeFunction* _tmp10_;
		_tmp10_ = function;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp10_, VALA_CCODE_MODIFIERS_STATIC);
	}
	_tmp11_ = function;
	_tmp12_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat ("const ", _tmp13_, NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strconcat (_tmp15_, "*", NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = vala_ccode_parameter_new ("self", _tmp17_);
	_tmp19_ = _tmp18_;
	vala_ccode_function_add_parameter (_tmp11_, _tmp19_);
	_vala_ccode_node_unref0 (_tmp19_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp13_);
	_tmp20_ = function;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp20_);
	_tmp21_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp22_ = _tmp21_;
	_tmp23_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp24_ = _tmp23_;
	_tmp25_ = g_strconcat (_tmp24_, "*", NULL);
	_tmp26_ = _tmp25_;
	_tmp27_ = vala_ccode_variable_declarator_new ("dup", NULL, NULL);
	_tmp28_ = _tmp27_;
	vala_ccode_function_add_declaration (_tmp22_, _tmp26_, (ValaCCodeDeclarator*) _tmp28_, 0);
	_vala_ccode_node_unref0 (_tmp28_);
	_g_free0 (_tmp26_);
	_g_free0 (_tmp24_);
	_tmp29_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp30_ = _tmp29_;
	_tmp31_ = vala_code_context_get_profile (_tmp30_);
	_tmp32_ = _tmp31_;
	if (_tmp32_ == VALA_PROFILE_GOBJECT) {
		ValaCCodeFunctionCall* creation_call = NULL;
		ValaCCodeIdentifier* _tmp33_;
		ValaCCodeIdentifier* _tmp34_;
		ValaCCodeFunctionCall* _tmp35_;
		ValaCCodeFunctionCall* _tmp36_;
		ValaCCodeFunctionCall* _tmp37_;
		gchar* _tmp38_;
		gchar* _tmp39_;
		ValaCCodeConstant* _tmp40_;
		ValaCCodeConstant* _tmp41_;
		ValaCCodeFunctionCall* _tmp42_;
		ValaCCodeConstant* _tmp43_;
		ValaCCodeConstant* _tmp44_;
		ValaCCodeFunction* _tmp45_;
		ValaCCodeFunction* _tmp46_;
		ValaCCodeIdentifier* _tmp47_;
		ValaCCodeIdentifier* _tmp48_;
		ValaCCodeFunctionCall* _tmp49_;
		_tmp33_ = vala_ccode_identifier_new ("g_new0");
		_tmp34_ = _tmp33_;
		_tmp35_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp34_);
		_tmp36_ = _tmp35_;
		_vala_ccode_node_unref0 (_tmp34_);
		creation_call = _tmp36_;
		_tmp37_ = creation_call;
		_tmp38_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp39_ = _tmp38_;
		_tmp40_ = vala_ccode_constant_new (_tmp39_);
		_tmp41_ = _tmp40_;
		vala_ccode_function_call_add_argument (_tmp37_, (ValaCCodeExpression*) _tmp41_);
		_vala_ccode_node_unref0 (_tmp41_);
		_g_free0 (_tmp39_);
		_tmp42_ = creation_call;
		_tmp43_ = vala_ccode_constant_new ("1");
		_tmp44_ = _tmp43_;
		vala_ccode_function_call_add_argument (_tmp42_, (ValaCCodeExpression*) _tmp44_);
		_vala_ccode_node_unref0 (_tmp44_);
		_tmp45_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp46_ = _tmp45_;
		_tmp47_ = vala_ccode_identifier_new ("dup");
		_tmp48_ = _tmp47_;
		_tmp49_ = creation_call;
		vala_ccode_function_add_assignment (_tmp46_, (ValaCCodeExpression*) _tmp48_, (ValaCCodeExpression*) _tmp49_);
		_vala_ccode_node_unref0 (_tmp48_);
		_vala_ccode_node_unref0 (creation_call);
	} else {
		ValaCodeContext* _tmp50_;
		ValaCodeContext* _tmp51_;
		ValaProfile _tmp52_;
		ValaProfile _tmp53_;
		_tmp50_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp51_ = _tmp50_;
		_tmp52_ = vala_code_context_get_profile (_tmp51_);
		_tmp53_ = _tmp52_;
		if (_tmp53_ == VALA_PROFILE_POSIX) {
			ValaCCodeFunctionCall* creation_call = NULL;
			ValaCCodeIdentifier* _tmp54_;
			ValaCCodeIdentifier* _tmp55_;
			ValaCCodeFunctionCall* _tmp56_;
			ValaCCodeFunctionCall* _tmp57_;
			ValaCCodeFunctionCall* _tmp58_;
			ValaCCodeConstant* _tmp59_;
			ValaCCodeConstant* _tmp60_;
			ValaCCodeFunctionCall* _tmp61_;
			gchar* _tmp62_;
			gchar* _tmp63_;
			gchar* _tmp64_;
			gchar* _tmp65_;
			ValaCCodeIdentifier* _tmp66_;
			ValaCCodeIdentifier* _tmp67_;
			ValaCCodeFunction* _tmp68_;
			ValaCCodeFunction* _tmp69_;
			ValaCCodeIdentifier* _tmp70_;
			ValaCCodeIdentifier* _tmp71_;
			ValaCCodeFunctionCall* _tmp72_;
			_tmp54_ = vala_ccode_identifier_new ("calloc");
			_tmp55_ = _tmp54_;
			_tmp56_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp55_);
			_tmp57_ = _tmp56_;
			_vala_ccode_node_unref0 (_tmp55_);
			creation_call = _tmp57_;
			_tmp58_ = creation_call;
			_tmp59_ = vala_ccode_constant_new ("1");
			_tmp60_ = _tmp59_;
			vala_ccode_function_call_add_argument (_tmp58_, (ValaCCodeExpression*) _tmp60_);
			_vala_ccode_node_unref0 (_tmp60_);
			_tmp61_ = creation_call;
			_tmp62_ = vala_get_ccode_name ((ValaCodeNode*) st);
			_tmp63_ = _tmp62_;
			_tmp64_ = g_strdup_printf ("sizeof (%s*)", _tmp63_);
			_tmp65_ = _tmp64_;
			_tmp66_ = vala_ccode_identifier_new (_tmp65_);
			_tmp67_ = _tmp66_;
			vala_ccode_function_call_add_argument (_tmp61_, (ValaCCodeExpression*) _tmp67_);
			_vala_ccode_node_unref0 (_tmp67_);
			_g_free0 (_tmp65_);
			_g_free0 (_tmp63_);
			_tmp68_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp69_ = _tmp68_;
			_tmp70_ = vala_ccode_identifier_new ("dup");
			_tmp71_ = _tmp70_;
			_tmp72_ = creation_call;
			vala_ccode_function_add_assignment (_tmp69_, (ValaCCodeExpression*) _tmp71_, (ValaCCodeExpression*) _tmp72_);
			_vala_ccode_node_unref0 (_tmp71_);
			_vala_ccode_node_unref0 (creation_call);
		}
	}
	if (vala_struct_is_disposable (st)) {
		ValaCCodeFunctionCall* copy_call = NULL;
		gchar* _tmp73_;
		gchar* _tmp74_;
		ValaCCodeIdentifier* _tmp75_;
		ValaCCodeIdentifier* _tmp76_;
		ValaCCodeFunctionCall* _tmp77_;
		ValaCCodeFunctionCall* _tmp78_;
		ValaCCodeFunctionCall* _tmp79_;
		ValaCCodeIdentifier* _tmp80_;
		ValaCCodeIdentifier* _tmp81_;
		ValaCCodeFunctionCall* _tmp82_;
		ValaCCodeIdentifier* _tmp83_;
		ValaCCodeIdentifier* _tmp84_;
		ValaCCodeFunction* _tmp85_;
		ValaCCodeFunction* _tmp86_;
		ValaCCodeFunctionCall* _tmp87_;
		_tmp73_ = vala_get_ccode_copy_function ((ValaTypeSymbol*) st);
		_tmp74_ = _tmp73_;
		_tmp75_ = vala_ccode_identifier_new (_tmp74_);
		_tmp76_ = _tmp75_;
		_tmp77_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp76_);
		_tmp78_ = _tmp77_;
		_vala_ccode_node_unref0 (_tmp76_);
		_g_free0 (_tmp74_);
		copy_call = _tmp78_;
		_tmp79_ = copy_call;
		_tmp80_ = vala_ccode_identifier_new ("self");
		_tmp81_ = _tmp80_;
		vala_ccode_function_call_add_argument (_tmp79_, (ValaCCodeExpression*) _tmp81_);
		_vala_ccode_node_unref0 (_tmp81_);
		_tmp82_ = copy_call;
		_tmp83_ = vala_ccode_identifier_new ("dup");
		_tmp84_ = _tmp83_;
		vala_ccode_function_call_add_argument (_tmp82_, (ValaCCodeExpression*) _tmp84_);
		_vala_ccode_node_unref0 (_tmp84_);
		_tmp85_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp86_ = _tmp85_;
		_tmp87_ = copy_call;
		vala_ccode_function_add_expression (_tmp86_, (ValaCCodeExpression*) _tmp87_);
		_vala_ccode_node_unref0 (copy_call);
	} else {
		ValaCCodeFile* _tmp88_;
		ValaCCodeFunctionCall* sizeof_call = NULL;
		ValaCCodeIdentifier* _tmp89_;
		ValaCCodeIdentifier* _tmp90_;
		ValaCCodeFunctionCall* _tmp91_;
		ValaCCodeFunctionCall* _tmp92_;
		ValaCCodeFunctionCall* _tmp93_;
		gchar* _tmp94_;
		gchar* _tmp95_;
		ValaCCodeConstant* _tmp96_;
		ValaCCodeConstant* _tmp97_;
		ValaCCodeFunctionCall* copy_call = NULL;
		ValaCCodeIdentifier* _tmp98_;
		ValaCCodeIdentifier* _tmp99_;
		ValaCCodeFunctionCall* _tmp100_;
		ValaCCodeFunctionCall* _tmp101_;
		ValaCCodeFunctionCall* _tmp102_;
		ValaCCodeIdentifier* _tmp103_;
		ValaCCodeIdentifier* _tmp104_;
		ValaCCodeFunctionCall* _tmp105_;
		ValaCCodeIdentifier* _tmp106_;
		ValaCCodeIdentifier* _tmp107_;
		ValaCCodeFunctionCall* _tmp108_;
		ValaCCodeFunctionCall* _tmp109_;
		ValaCCodeFunction* _tmp110_;
		ValaCCodeFunction* _tmp111_;
		ValaCCodeFunctionCall* _tmp112_;
		_tmp88_ = ((ValaCCodeBaseModule*) self)->cfile;
		vala_ccode_file_add_include (_tmp88_, "string.h", FALSE);
		_tmp89_ = vala_ccode_identifier_new ("sizeof");
		_tmp90_ = _tmp89_;
		_tmp91_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp90_);
		_tmp92_ = _tmp91_;
		_vala_ccode_node_unref0 (_tmp90_);
		sizeof_call = _tmp92_;
		_tmp93_ = sizeof_call;
		_tmp94_ = vala_get_ccode_name ((ValaCodeNode*) st);
		_tmp95_ = _tmp94_;
		_tmp96_ = vala_ccode_constant_new (_tmp95_);
		_tmp97_ = _tmp96_;
		vala_ccode_function_call_add_argument (_tmp93_, (ValaCCodeExpression*) _tmp97_);
		_vala_ccode_node_unref0 (_tmp97_);
		_g_free0 (_tmp95_);
		_tmp98_ = vala_ccode_identifier_new ("memcpy");
		_tmp99_ = _tmp98_;
		_tmp100_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp99_);
		_tmp101_ = _tmp100_;
		_vala_ccode_node_unref0 (_tmp99_);
		copy_call = _tmp101_;
		_tmp102_ = copy_call;
		_tmp103_ = vala_ccode_identifier_new ("dup");
		_tmp104_ = _tmp103_;
		vala_ccode_function_call_add_argument (_tmp102_, (ValaCCodeExpression*) _tmp104_);
		_vala_ccode_node_unref0 (_tmp104_);
		_tmp105_ = copy_call;
		_tmp106_ = vala_ccode_identifier_new ("self");
		_tmp107_ = _tmp106_;
		vala_ccode_function_call_add_argument (_tmp105_, (ValaCCodeExpression*) _tmp107_);
		_vala_ccode_node_unref0 (_tmp107_);
		_tmp108_ = copy_call;
		_tmp109_ = sizeof_call;
		vala_ccode_function_call_add_argument (_tmp108_, (ValaCCodeExpression*) _tmp109_);
		_tmp110_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp111_ = _tmp110_;
		_tmp112_ = copy_call;
		vala_ccode_function_add_expression (_tmp111_, (ValaCCodeExpression*) _tmp112_);
		_vala_ccode_node_unref0 (copy_call);
		_vala_ccode_node_unref0 (sizeof_call);
	}
	_tmp113_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp114_ = _tmp113_;
	_tmp115_ = vala_ccode_identifier_new ("dup");
	_tmp116_ = _tmp115_;
	vala_ccode_function_add_return (_tmp114_, (ValaCCodeExpression*) _tmp116_);
	_vala_ccode_node_unref0 (_tmp116_);
	vala_ccode_base_module_pop_function ((ValaCCodeBaseModule*) self);
	_tmp117_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp118_ = function;
	vala_ccode_file_add_function (_tmp117_, _tmp118_);
	_vala_ccode_node_unref0 (function);
}


static void
vala_ccode_struct_module_add_struct_free_function (ValaCCodeStructModule* self,
                                                   ValaStruct* st)
{
	ValaCCodeFunction* function = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	ValaCCodeFunction* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	ValaCCodeParameter* _tmp16_;
	ValaCCodeParameter* _tmp17_;
	ValaCCodeFunction* _tmp18_;
	ValaCodeContext* _tmp31_;
	ValaCodeContext* _tmp32_;
	ValaProfile _tmp33_;
	ValaProfile _tmp34_;
	ValaCCodeFile* _tmp59_;
	ValaCCodeFunction* _tmp60_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = vala_get_ccode_free_function ((ValaTypeSymbol*) st);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_ccode_function_new (_tmp1_, "void");
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	function = _tmp3_;
	if (vala_symbol_is_private_symbol ((ValaSymbol*) st)) {
		ValaCCodeFunction* _tmp4_;
		_tmp4_ = function;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp4_, VALA_CCODE_MODIFIERS_STATIC);
	} else {
		gboolean _tmp5_ = FALSE;
		ValaCodeContext* _tmp6_;
		ValaCodeContext* _tmp7_;
		gboolean _tmp8_;
		gboolean _tmp9_;
		_tmp6_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp7_ = _tmp6_;
		_tmp8_ = vala_code_context_get_hide_internal (_tmp7_);
		_tmp9_ = _tmp8_;
		if (_tmp9_) {
			_tmp5_ = vala_symbol_is_internal_symbol ((ValaSymbol*) st);
		} else {
			_tmp5_ = FALSE;
		}
		if (_tmp5_) {
			ValaCCodeFunction* _tmp10_;
			_tmp10_ = function;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp10_, VALA_CCODE_MODIFIERS_INTERNAL);
		}
	}
	_tmp11_ = function;
	_tmp12_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat (_tmp13_, "*", NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = vala_ccode_parameter_new ("self", _tmp15_);
	_tmp17_ = _tmp16_;
	vala_ccode_function_add_parameter (_tmp11_, _tmp17_);
	_vala_ccode_node_unref0 (_tmp17_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp13_);
	_tmp18_ = function;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp18_);
	if (vala_struct_is_disposable (st)) {
		ValaCCodeFunctionCall* destroy_call = NULL;
		gchar* _tmp19_;
		gchar* _tmp20_;
		ValaCCodeIdentifier* _tmp21_;
		ValaCCodeIdentifier* _tmp22_;
		ValaCCodeFunctionCall* _tmp23_;
		ValaCCodeFunctionCall* _tmp24_;
		ValaCCodeFunctionCall* _tmp25_;
		ValaCCodeIdentifier* _tmp26_;
		ValaCCodeIdentifier* _tmp27_;
		ValaCCodeFunction* _tmp28_;
		ValaCCodeFunction* _tmp29_;
		ValaCCodeFunctionCall* _tmp30_;
		_tmp19_ = vala_get_ccode_destroy_function ((ValaTypeSymbol*) st);
		_tmp20_ = _tmp19_;
		_tmp21_ = vala_ccode_identifier_new (_tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp22_);
		_tmp24_ = _tmp23_;
		_vala_ccode_node_unref0 (_tmp22_);
		_g_free0 (_tmp20_);
		destroy_call = _tmp24_;
		_tmp25_ = destroy_call;
		_tmp26_ = vala_ccode_identifier_new ("self");
		_tmp27_ = _tmp26_;
		vala_ccode_function_call_add_argument (_tmp25_, (ValaCCodeExpression*) _tmp27_);
		_vala_ccode_node_unref0 (_tmp27_);
		_tmp28_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp29_ = _tmp28_;
		_tmp30_ = destroy_call;
		vala_ccode_function_add_expression (_tmp29_, (ValaCCodeExpression*) _tmp30_);
		_vala_ccode_node_unref0 (destroy_call);
	}
	_tmp31_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp32_ = _tmp31_;
	_tmp33_ = vala_code_context_get_profile (_tmp32_);
	_tmp34_ = _tmp33_;
	if (_tmp34_ == VALA_PROFILE_GOBJECT) {
		ValaCCodeFunctionCall* free_call = NULL;
		ValaCCodeIdentifier* _tmp35_;
		ValaCCodeIdentifier* _tmp36_;
		ValaCCodeFunctionCall* _tmp37_;
		ValaCCodeFunctionCall* _tmp38_;
		ValaCCodeFunctionCall* _tmp39_;
		ValaCCodeIdentifier* _tmp40_;
		ValaCCodeIdentifier* _tmp41_;
		ValaCCodeFunction* _tmp42_;
		ValaCCodeFunction* _tmp43_;
		ValaCCodeFunctionCall* _tmp44_;
		_tmp35_ = vala_ccode_identifier_new ("g_free");
		_tmp36_ = _tmp35_;
		_tmp37_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp36_);
		_tmp38_ = _tmp37_;
		_vala_ccode_node_unref0 (_tmp36_);
		free_call = _tmp38_;
		_tmp39_ = free_call;
		_tmp40_ = vala_ccode_identifier_new ("self");
		_tmp41_ = _tmp40_;
		vala_ccode_function_call_add_argument (_tmp39_, (ValaCCodeExpression*) _tmp41_);
		_vala_ccode_node_unref0 (_tmp41_);
		_tmp42_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp43_ = _tmp42_;
		_tmp44_ = free_call;
		vala_ccode_function_add_expression (_tmp43_, (ValaCCodeExpression*) _tmp44_);
		_vala_ccode_node_unref0 (free_call);
	} else {
		ValaCodeContext* _tmp45_;
		ValaCodeContext* _tmp46_;
		ValaProfile _tmp47_;
		ValaProfile _tmp48_;
		_tmp45_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp46_ = _tmp45_;
		_tmp47_ = vala_code_context_get_profile (_tmp46_);
		_tmp48_ = _tmp47_;
		if (_tmp48_ == VALA_PROFILE_POSIX) {
			ValaCCodeFunctionCall* free_call = NULL;
			ValaCCodeIdentifier* _tmp49_;
			ValaCCodeIdentifier* _tmp50_;
			ValaCCodeFunctionCall* _tmp51_;
			ValaCCodeFunctionCall* _tmp52_;
			ValaCCodeFunctionCall* _tmp53_;
			ValaCCodeIdentifier* _tmp54_;
			ValaCCodeIdentifier* _tmp55_;
			ValaCCodeFunction* _tmp56_;
			ValaCCodeFunction* _tmp57_;
			ValaCCodeFunctionCall* _tmp58_;
			_tmp49_ = vala_ccode_identifier_new ("free");
			_tmp50_ = _tmp49_;
			_tmp51_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp50_);
			_tmp52_ = _tmp51_;
			_vala_ccode_node_unref0 (_tmp50_);
			free_call = _tmp52_;
			_tmp53_ = free_call;
			_tmp54_ = vala_ccode_identifier_new ("self");
			_tmp55_ = _tmp54_;
			vala_ccode_function_call_add_argument (_tmp53_, (ValaCCodeExpression*) _tmp55_);
			_vala_ccode_node_unref0 (_tmp55_);
			_tmp56_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp57_ = _tmp56_;
			_tmp58_ = free_call;
			vala_ccode_function_add_expression (_tmp57_, (ValaCCodeExpression*) _tmp58_);
			_vala_ccode_node_unref0 (free_call);
		}
	}
	vala_ccode_base_module_pop_function ((ValaCCodeBaseModule*) self);
	_tmp59_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp60_ = function;
	vala_ccode_file_add_function (_tmp59_, _tmp60_);
	_vala_ccode_node_unref0 (function);
}


static void
vala_ccode_struct_module_add_struct_copy_function (ValaCCodeStructModule* self,
                                                   ValaStruct* st)
{
	ValaCCodeFunction* function = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	ValaCCodeFunction* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	ValaCCodeParameter* _tmp18_;
	ValaCCodeParameter* _tmp19_;
	ValaCCodeFunction* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	ValaCCodeParameter* _tmp25_;
	ValaCCodeParameter* _tmp26_;
	ValaCCodeFunction* _tmp27_;
	ValaGLibValue* dest_struct = NULL;
	ValaDataType* _tmp28_;
	ValaDataType* _tmp29_;
	ValaCCodeIdentifier* _tmp30_;
	ValaCCodeIdentifier* _tmp31_;
	ValaGLibValue* _tmp32_;
	ValaGLibValue* _tmp33_;
	ValaCCodeFile* _tmp64_;
	ValaCCodeFunction* _tmp65_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = vala_get_ccode_copy_function ((ValaTypeSymbol*) st);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_ccode_function_new (_tmp1_, "void");
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	function = _tmp3_;
	if (vala_symbol_is_private_symbol ((ValaSymbol*) st)) {
		ValaCCodeFunction* _tmp4_;
		_tmp4_ = function;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp4_, VALA_CCODE_MODIFIERS_STATIC);
	} else {
		gboolean _tmp5_ = FALSE;
		ValaCodeContext* _tmp6_;
		ValaCodeContext* _tmp7_;
		gboolean _tmp8_;
		gboolean _tmp9_;
		_tmp6_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp7_ = _tmp6_;
		_tmp8_ = vala_code_context_get_hide_internal (_tmp7_);
		_tmp9_ = _tmp8_;
		if (_tmp9_) {
			_tmp5_ = vala_symbol_is_internal_symbol ((ValaSymbol*) st);
		} else {
			_tmp5_ = FALSE;
		}
		if (_tmp5_) {
			ValaCCodeFunction* _tmp10_;
			_tmp10_ = function;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp10_, VALA_CCODE_MODIFIERS_INTERNAL);
		}
	}
	_tmp11_ = function;
	_tmp12_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat ("const ", _tmp13_, NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strconcat (_tmp15_, "*", NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = vala_ccode_parameter_new ("self", _tmp17_);
	_tmp19_ = _tmp18_;
	vala_ccode_function_add_parameter (_tmp11_, _tmp19_);
	_vala_ccode_node_unref0 (_tmp19_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp13_);
	_tmp20_ = function;
	_tmp21_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp22_ = _tmp21_;
	_tmp23_ = g_strconcat (_tmp22_, "*", NULL);
	_tmp24_ = _tmp23_;
	_tmp25_ = vala_ccode_parameter_new ("dest", _tmp24_);
	_tmp26_ = _tmp25_;
	vala_ccode_function_add_parameter (_tmp20_, _tmp26_);
	_vala_ccode_node_unref0 (_tmp26_);
	_g_free0 (_tmp24_);
	_g_free0 (_tmp22_);
	_tmp27_ = function;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp27_);
	_tmp28_ = vala_ccode_base_module_get_data_type_for_symbol ((ValaTypeSymbol*) st);
	_tmp29_ = _tmp28_;
	_tmp30_ = vala_ccode_identifier_new ("(*dest)");
	_tmp31_ = _tmp30_;
	_tmp32_ = vala_glib_value_new (_tmp29_, (ValaCCodeExpression*) _tmp31_, TRUE);
	_tmp33_ = _tmp32_;
	_vala_ccode_node_unref0 (_tmp31_);
	_vala_code_node_unref0 (_tmp29_);
	dest_struct = _tmp33_;
	{
		ValaList* _f_list = NULL;
		ValaList* _tmp34_;
		gint _f_size = 0;
		ValaList* _tmp35_;
		gint _tmp36_;
		gint _tmp37_;
		gint _f_index = 0;
		_tmp34_ = vala_struct_get_fields (st);
		_f_list = _tmp34_;
		_tmp35_ = _f_list;
		_tmp36_ = vala_collection_get_size ((ValaCollection*) _tmp35_);
		_tmp37_ = _tmp36_;
		_f_size = _tmp37_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp38_;
			gint _tmp39_;
			gint _tmp40_;
			ValaField* f = NULL;
			ValaList* _tmp41_;
			gint _tmp42_;
			gpointer _tmp43_;
			ValaField* _tmp44_;
			ValaMemberBinding _tmp45_;
			ValaMemberBinding _tmp46_;
			_tmp38_ = _f_index;
			_f_index = _tmp38_ + 1;
			_tmp39_ = _f_index;
			_tmp40_ = _f_size;
			if (!(_tmp39_ < _tmp40_)) {
				break;
			}
			_tmp41_ = _f_list;
			_tmp42_ = _f_index;
			_tmp43_ = vala_list_get (_tmp41_, _tmp42_);
			f = (ValaField*) _tmp43_;
			_tmp44_ = f;
			_tmp45_ = vala_field_get_binding (_tmp44_);
			_tmp46_ = _tmp45_;
			if (_tmp46_ == VALA_MEMBER_BINDING_INSTANCE) {
				ValaTargetValue* value = NULL;
				ValaField* _tmp47_;
				ValaTargetValue* _tmp48_;
				ValaTargetValue* _tmp49_;
				ValaTargetValue* _tmp50_;
				ValaTargetValue* _tmp51_;
				gboolean _tmp52_ = FALSE;
				ValaField* _tmp53_;
				ValaField* _tmp61_;
				ValaGLibValue* _tmp62_;
				ValaTargetValue* _tmp63_;
				_tmp47_ = f;
				_tmp48_ = vala_ccode_base_module_load_this_parameter ((ValaCCodeBaseModule*) self, G_TYPE_CHECK_INSTANCE_CAST (st, VALA_TYPE_TYPESYMBOL, ValaTypeSymbol));
				_tmp49_ = _tmp48_;
				_tmp50_ = vala_code_generator_load_field ((ValaCodeGenerator*) self, _tmp47_, _tmp49_);
				_tmp51_ = _tmp50_;
				_vala_target_value_unref0 (_tmp49_);
				value = _tmp51_;
				_tmp53_ = f;
				if (vala_get_ccode_delegate_target ((ValaCodeNode*) _tmp53_)) {
					ValaField* _tmp54_;
					ValaDataType* _tmp55_;
					ValaDataType* _tmp56_;
					_tmp54_ = f;
					_tmp55_ = vala_variable_get_variable_type ((ValaVariable*) _tmp54_);
					_tmp56_ = _tmp55_;
					_tmp52_ = vala_ccode_base_module_requires_copy ((ValaCCodeBaseModule*) self, _tmp56_);
				} else {
					_tmp52_ = FALSE;
				}
				if (_tmp52_) {
					ValaTargetValue* _tmp57_;
					ValaField* _tmp58_;
					ValaTargetValue* _tmp59_;
					ValaTargetValue* _tmp60_;
					_tmp57_ = value;
					_tmp58_ = f;
					_tmp59_ = vala_ccode_base_module_copy_value ((ValaCCodeBaseModule*) self, _tmp57_, (ValaCodeNode*) _tmp58_);
					_vala_target_value_unref0 (value);
					value = _tmp59_;
					_tmp60_ = value;
					if (_tmp60_ == NULL) {
						_vala_target_value_unref0 (value);
						_vala_code_node_unref0 (f);
						continue;
					}
				}
				_tmp61_ = f;
				_tmp62_ = dest_struct;
				_tmp63_ = value;
				vala_code_generator_store_field ((ValaCodeGenerator*) self, _tmp61_, (ValaTargetValue*) _tmp62_, _tmp63_, NULL);
				_vala_target_value_unref0 (value);
			}
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	vala_ccode_base_module_pop_function ((ValaCCodeBaseModule*) self);
	_tmp64_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp65_ = function;
	vala_ccode_file_add_function (_tmp64_, _tmp65_);
	_vala_target_value_unref0 (dest_struct);
	_vala_ccode_node_unref0 (function);
}


static void
vala_ccode_struct_module_begin_struct_destroy_function (ValaCCodeStructModule* self,
                                                        ValaStruct* st)
{
	ValaCCodeBaseModuleEmitContext* _tmp0_;
	ValaCCodeFunction* function = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	ValaCCodeFunction* _tmp4_;
	ValaCCodeFunction* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	ValaCCodeParameter* _tmp17_;
	ValaCCodeParameter* _tmp18_;
	ValaCCodeFunction* _tmp19_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = ((ValaCCodeBaseModule*) self)->instance_finalize_context;
	vala_ccode_base_module_push_context ((ValaCCodeBaseModule*) self, _tmp0_);
	_tmp1_ = vala_get_ccode_destroy_function ((ValaTypeSymbol*) st);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_ccode_function_new (_tmp2_, "void");
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	function = _tmp4_;
	if (vala_symbol_is_private_symbol ((ValaSymbol*) st)) {
		ValaCCodeFunction* _tmp5_;
		_tmp5_ = function;
		vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp5_, VALA_CCODE_MODIFIERS_STATIC);
	} else {
		gboolean _tmp6_ = FALSE;
		ValaCodeContext* _tmp7_;
		ValaCodeContext* _tmp8_;
		gboolean _tmp9_;
		gboolean _tmp10_;
		_tmp7_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp8_ = _tmp7_;
		_tmp9_ = vala_code_context_get_hide_internal (_tmp8_);
		_tmp10_ = _tmp9_;
		if (_tmp10_) {
			_tmp6_ = vala_symbol_is_internal_symbol ((ValaSymbol*) st);
		} else {
			_tmp6_ = FALSE;
		}
		if (_tmp6_) {
			ValaCCodeFunction* _tmp11_;
			_tmp11_ = function;
			vala_ccode_node_set_modifiers ((ValaCCodeNode*) _tmp11_, VALA_CCODE_MODIFIERS_INTERNAL);
		}
	}
	_tmp12_ = function;
	_tmp13_ = vala_get_ccode_name ((ValaCodeNode*) st);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strconcat (_tmp14_, "*", NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = vala_ccode_parameter_new ("self", _tmp16_);
	_tmp18_ = _tmp17_;
	vala_ccode_function_add_parameter (_tmp12_, _tmp18_);
	_vala_ccode_node_unref0 (_tmp18_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp14_);
	_tmp19_ = function;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp19_);
	vala_ccode_base_module_pop_context ((ValaCCodeBaseModule*) self);
	_vala_ccode_node_unref0 (function);
}


static void
vala_ccode_struct_module_add_struct_destroy_function (ValaCCodeStructModule* self,
                                                      ValaStruct* st)
{
	ValaCCodeFile* _tmp0_;
	ValaCCodeBaseModuleEmitContext* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp1_ = ((ValaCCodeBaseModule*) self)->instance_finalize_context;
	_tmp2_ = _tmp1_->ccode;
	vala_ccode_file_add_function (_tmp0_, _tmp2_);
}


ValaCCodeStructModule*
vala_ccode_struct_module_construct (GType object_type)
{
	ValaCCodeStructModule* self = NULL;
	self = (ValaCCodeStructModule*) vala_ccode_base_module_construct (object_type);
	return self;
}


static void
vala_ccode_struct_module_class_init (ValaCCodeStructModuleClass * klass)
{
	vala_ccode_struct_module_parent_class = g_type_class_peek_parent (klass);
	((ValaCCodeBaseModuleClass *) klass)->generate_struct_declaration = (void (*) (ValaCCodeBaseModule*, ValaStruct*, ValaCCodeFile*)) vala_ccode_struct_module_real_generate_struct_declaration;
	((ValaCodeVisitorClass *) klass)->visit_struct = (void (*) (ValaCodeVisitor*, ValaStruct*)) vala_ccode_struct_module_real_visit_struct;
}


static void
vala_ccode_struct_module_instance_init (ValaCCodeStructModule * self)
{
}


GType
vala_ccode_struct_module_get_type (void)
{
	static volatile gsize vala_ccode_struct_module_type_id__volatile = 0;
	if (g_once_init_enter (&vala_ccode_struct_module_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaCCodeStructModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_ccode_struct_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaCCodeStructModule), 0, (GInstanceInitFunc) vala_ccode_struct_module_instance_init, NULL };
		GType vala_ccode_struct_module_type_id;
		vala_ccode_struct_module_type_id = g_type_register_static (VALA_TYPE_CCODE_BASE_MODULE, "ValaCCodeStructModule", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&vala_ccode_struct_module_type_id__volatile, vala_ccode_struct_module_type_id);
	}
	return vala_ccode_struct_module_type_id__volatile;
}



